### ISSUE TITLE
Error on sign page when user creates an account and clicks on signup button

### ISSUE THREAD

**Issue by Rohan-RPJ** [FullBinaryAlchemist/vocab-builder#6]
![Screenshot_2019-04-06-01-50-39](https://user-images.githubusercontent.com/43491049/55666389-fcf26600-586b-11e9-8265-ec166f89f510.png)
The above error is encountered when user creates a new account but after refreshing this page user is redirected back to signup page with Account created message

**Comment by FullBinaryAlchemist** [comment]
Resolved. Added namespaced urls to the templates. i.e using ```'register:signup'``` instead of just ```'signup'```
